### ISSUE TITLE
Adding a / to end of a post URL gives a page not found.

### ISSUE THREAD

**Issue by ruledby** [ruqqus/ruqqus#353]
## Expected Behavior
I should be able to see the post.

## Current Behavior
I get a 404 page not found, maybe thinks its a directory or looking for a comment id.

## Possible Solution

Have the web server ignore or trim trailing "/".

## Steps to Reproduce

1. Take any post (https://ruqqus.com/post/1isw/since-fedora-33-is-changing-to)
2. Add a / to the url (https://ruqqus.com/post/1isw/since-fedora-33-is-changing-to/)
3. Take a comment URL (https://ruqqus.com/post/1ig1/i-have-no-interest-in-politics/4rk9)
4. Add a / to the url (https://ruqqus.com/post/1ig1/i-have-no-interest-in-politics/4rk9/)

## Context (Environment)

So, this isn't a major issue by any means, I only found it because I was reading nested comments, I removed the comment id from the url thinking it'd take me back to the main post.  This also happens if you add a "/" to the end of a comment url"

**Comment by noahmaranesi** [comment]
Also applies to Guilds: https://ruqqus.com/+Ruqqus/

I mentioned it a while ago (when I joined in April), but nothing's been done yet 😕

**Comment by init-i** [comment]
This would be easily fixed by disabling [strict_slashes](https://werkzeug.palletsprojects.com/en/1.0.x/routing/#rule-format). You just need to add

```python
app.url_map.strict_slahes = False
```
somewhere in `__main__.py`

It would route '/X/' to '/X' but I'm not sure if that's the behaviour the admins want.

**Comment by coldfission** [comment]
I recommend redirecting to remove the trailing slash so that any potential SEO juice is centralized to one specific URL

**Comment by lithiumjs** [comment]
fixed quite some time ago.

**Comment by ruledby** [comment]
![without_slash](https://user-images.githubusercontent.com/3304201/97783885-ddaae000-1b57-11eb-8e61-cc71ad2e170a.PNG)

![with_slash](https://user-images.githubusercontent.com/3304201/97783887-e13e6700-1b57-11eb-8b50-6575dd19fdec.PNG)


Here are screenshots taken just now.  I double checked this issue for posts/comments/guilds.  The only thing changed was adding a "/" to the end of the address.  This was reproduced using Chrome/Firefox for Windows, Safari/Firefox on macOS.

**Comment by noahmaranesi** [comment]
> fixed quite some time ago.

@lithiumjs

See these URLs, they ***all*** return 404:

- https://ruqqus.com/+Ruqqus/

- https://ruqqus.com/+Ruqqus/post/4fzo/vue-is-important-but-we-need/

- https://ruqqus.com/@captainmeta4/

Please do not close issues **when they are definitely not fixed**.

**Comment by arkit3kt** [comment]
https://github.com/ruqqus/ruqqus/commit/9d76051b14192bfe7ec68a62451e0e7fde917327
